ALTER TABLE pancakes_with_ingredients
    ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT FIRST,
    ADD PRIMARY KEY (id),
    ADD UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE;

ALTER TABLE user_roles
    ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT FIRST,
    ADD PRIMARY KEY (id),
    ADD UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE;